# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'TTStackView' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TTStackView
  pod 'SDWebImage'
  pod 'Masonry'
  pod 'Reveal-iOS-SDK', :configurations => ['Debug']

end
