# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'LearnAutoLayout' do
  use_frameworks!

  pod 'SnapKit', '~> 4.2.0'
  pod 'Kingfisher', '~> 5.2.0'

end
